### ISSUE TITLE
Issue running a local instance: app error: Response body must respond to each (Rack::Lint::LintError)

### ISSUE THREAD

**Issue by jbrinksmeier** [lineofflight/frankfurter#19]
Hi

I'm trying to evaluate whether I can run my own instance of frankfurter (while it's much appreciated that you provide a public instance, I don't want to stress it).
When I run a `docker-compose up`, frankfurter responds well with the startpage 
```
* Rebuilt URL to: localhost:8080/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 06 Apr 2021 11:07:03 GMT
< Connection: close
< Content-Type: application/json; charset=utf-8
< Content-Length: 43
< Vary: Origin
< 
* Closing connection 0
{"docs":"https://www.frankfurter.app/docs"}
```

When hitting `localhost:8080/latest` it responds with an error though:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /latest HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 422 Unprocessable Entity
< Date: Tue, 06 Apr 2021 11:08:00 GMT
< Connection: close
< Vary: Origin
< Transfer-Encoding: chunked
< 
* Illegal or missing hexadecimal sequence in chunked-encoding
* stopped the pause stream!
* Closing connection 0
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```

The app logs state this:
```
web    | 172.28.0.1 - - [06/Apr/2021:10:51:37 +0000] "GET /latest HTTP/1.1" 422 - 0.0024
web    | E, [2021-04-06T10:51:37.509108 #22] ERROR -- : app error: Response body must respond to each (Rack::Lint::LintError)
web    | E, [2021-04-06T10:51:37.509182 #22] ERROR -- : /usr/local/bundle/gems/rack-2.2.3/lib/rack/lint.rb:21:in `assert'
web    | E, [2021-04-06T10:51:37.509209 #22] ERROR -- : /usr/local/bundle/gems/rack-2.2.3/lib/rack/lint.rb:750:in `each'
web    | E, [2021-04-06T10:51:37.509226 #22] ERROR -- : /usr/local/bundle/gems/rack-2.2.3/lib/rack/body_proxy.rb:41:in `method_missing'
web    | E, [2021-04-06T10:51:37.509245 #22] ERROR -- : /usr/local/bundle/gems/rack-2.2.3/lib/rack/chunked.rb:38:in `each'
web    | E, [2021-04-06T10:51:37.509261 #22] ERROR -- : /usr/local/bundle/gems/unicorn-5.5.5/lib/unicorn/http_response.rb:58:in `http_response_write'
web    | E, [2021-04-06T10:51:37.509280 #22] ERROR -- : /usr/local/bundle/gems/unicorn-5.5.5/lib/unicorn/http_server.rb:616:in `process_client'
web    | E, [2021-04-06T10:51:37.509297 #22] ERROR -- : /usr/local/bundle/gems/unicorn-5.5.5/lib/unicorn/http_server.rb:701:in `worker_loop'
web    | E, [2021-04-06T10:51:37.509316 #22] ERROR -- : /usr/local/bundle/gems/unicorn-5.5.5/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
web    | E, [2021-04-06T10:51:37.509337 #22] ERROR -- : /usr/local/bundle/gems/unicorn-5.5.5/lib/unicorn/http_server.rb:144:in `start'
web    | E, [2021-04-06T10:51:37.509354 #22] ERROR -- : /usr/local/bundle/gems/unicorn-5.5.5/bin/unicorn:128:in `<top (required)>'
web    | E, [2021-04-06T10:51:37.509370 #22] ERROR -- : /usr/local/bundle/bin/unicorn:23:in `load'
web    | E, [2021-04-06T10:51:37.509389 #22] ERROR -- : /usr/local/bundle/bin/unicorn:23:in `<top (required)>'
web    | E, [2021-04-06T10:51:37.509407 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
web    | E, [2021-04-06T10:51:37.509426 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
web    | E, [2021-04-06T10:51:37.509443 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
web    | E, [2021-04-06T10:51:37.509462 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
web    | E, [2021-04-06T10:51:37.509480 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
web    | E, [2021-04-06T10:51:37.509499 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
web    | E, [2021-04-06T10:51:37.509519 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
web    | E, [2021-04-06T10:51:37.509539 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
web    | E, [2021-04-06T10:51:37.509559 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
web    | E, [2021-04-06T10:51:37.509581 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
web    | E, [2021-04-06T10:51:37.509600 #22] ERROR -- : /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
web    | E, [2021-04-06T10:51:37.509615 #22] ERROR -- : /usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
web    | E, [2021-04-06T10:51:37.509633 #22] ERROR -- : /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
web    | E, [2021-04-06T10:51:37.509649 #22] ERROR -- : /usr/local/bundle/bin/bundle:23:in `load'
web    | E, [2021-04-06T10:51:37.509667 #22] ERROR -- : /usr/local/bundle/bin/bundle:23:in `<main>'
```

My ruby foo is absolutely rusty, and I'm afraid I'm unable to debug this properly.  Build went fine, postgres looks fine, too. Would you be willing to help me debug this?

Thanks in advance!

**Comment by jbrinksmeier** [comment]
Made some progress. The underlying error supposedly was `NameError: uninitialized constant Quote::EndOfDay::Digest`, I got there after disabling the error_handler plugin.

Adding `require 'digest'` to `lib/quote/end_of_day.rb` fixed this issue for me now. Please advice if you think that is a general error. I will happily open a PR then :)

**Comment by hakanensari** [comment]
@jbrinksmeier, not sure why this has not bubbled up elsewhere, but yes, please do open a PR, thanks!
